<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addres</name>
   <tag></tag>
   <elementGuidId>55fd7fc7-88cb-4939-97e1-5c17d7cdc0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[.='Address']/following-sibling::td/child::textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[.='Address']/following-sibling::td/child::textarea</value>
   </webElementProperties>
</WebElementEntity>
