<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email</name>
   <tag></tag>
   <elementGuidId>a12f53a2-335b-4067-9f82-123ccc21f675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[.='Email']/following-sibling::td/child::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[.='Email']/following-sibling::td/child::input</value>
   </webElementProperties>
</WebElementEntity>
