<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name</name>
   <tag></tag>
   <elementGuidId>7ee87fc4-57f9-4546-90ee-f71496fffef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[.='Name']/following-sibling::td/child::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[.='Name']/following-sibling::td/child::input</value>
   </webElementProperties>
</WebElementEntity>
