<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total</name>
   <tag></tag>
   <elementGuidId>3524b9b2-dcca-450b-a23f-eed47b93e709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[.='Total']/following-sibling::td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[.='Total']/following-sibling::td</value>
   </webElementProperties>
</WebElementEntity>
