<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_listitem</name>
   <tag></tag>
   <elementGuidId>19a5d642-2331-4f14-8d66-381fb6a366a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='cart_list']//div/descendant::button[.='Remove']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='cart_list']//div/descendant::button[.='Remove']</value>
   </webElementProperties>
</WebElementEntity>
