<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cartitem1</name>
   <tag></tag>
   <elementGuidId>c7fd2168-92e6-4146-bae2-d6de0fddbf66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='cart_list']/div[3]//div[@class='inventory_item_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='cart_list']/div[3]//div[@class='inventory_item_price']</value>
   </webElementProperties>
</WebElementEntity>
