<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cartitem2</name>
   <tag></tag>
   <elementGuidId>5218c83e-5385-4954-8158-01c09653f099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='cart_list']/div[4]//div[@class='inventory_item_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='cart_list']/div[4]//div[@class='inventory_item_price']</value>
   </webElementProperties>
</WebElementEntity>
