<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btntry</name>
   <tag></tag>
   <elementGuidId>63f50a7c-ece7-4cd9-91ef-f99ae59fe1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='tryit.asp?filename=tryjs_alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='tryit.asp?filename=tryjs_alert']</value>
   </webElementProperties>
</WebElementEntity>
