<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appstore</name>
   <tag></tag>
   <elementGuidId>f583c192-6744-4deb-b666-8f7d3732e9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src='/assets/img/app-stores.png?v=1642129329']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/assets/img/app-stores.png?v=1642129329']</value>
   </webElementProperties>
</WebElementEntity>
