<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>googleplay</name>
   <tag></tag>
   <elementGuidId>823e98aa-c331-4582-9212-0b0cd1168562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src='/assets/img/google-plays.png?v=1642129329']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/assets/img/google-plays.png?v=1642129329']</value>
   </webElementProperties>
</WebElementEntity>
